FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER user
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB federation_service

# Copy initialization scripts to docker-entrypoint-initdb.d
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the desired port
EXPOSE 5433